# Config section
Config:
  Plugin:
    # Config if the Shop plugin is enabled.
    # If set to true, jobs will give some coins. These values are configurable
    # If set to false, jobs will only give xp.
    Shop:
      enabled:true
  # Experience needed equation :
  # xp_level_one * level^first_coef - second_coef * xp_level_one * (level - substract_value)^third_coef
  Experience:
    xp_level_one:10
    first_coef:2.475
    second_coef:2.0
    substract_value:1.0
    third_coef:2.145
  # Set the different value of xp and coins give by the current job
  Jobs:
    Breeder:
      HORSE:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      DONKEY:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      SHEEP:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      COW:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      MUSHROOM_COW:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      PIG:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      CHICKEN:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      CAT:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      OCELOT:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      RABBIT:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      LLAMA:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      TURTLE:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      PANDA:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      FOX:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      BEE:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      HOGLIN:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
      STRIDER:
        Breed:
          xp:5
          coins:0.5
        Kill:
          xp:3
          coins:0.5
    Digger:
      DIRT:
        xp:3
        coins:0.15
      GRASS_BLOCK:
        xp:3
        coins:0.15
      COARSE_DIRT:
        xp:3
        coins:0.15
      GRAVEL:
        xp:3
        coins:0.15
      SAND:
        xp:2
        coins:0.1
      RED_SAND:
        xp:2
        coins:0.1
      SOUL_SAND:
        xp:5
        coins:0.25
      SOUL_SOIL:
        xp:5
        coins:0.25
      CLAY:
        xp:3
        coins:0.15
      MYCELIUM:
        xp:5
        coins:0.25
    Farmer:
      MELON:
        xp:2
        coins:0.2
      PUMPKIN:
        xp:2
        coins:0.2
      POTATOES:
        xp:2
        coins:0.2
      CARROT:
        xp:2
        coins:0.2
      BEETROOT:
        xp:2
        coins:0.2
      WHEAT:
        xp:2
        coins:0.2
      COCOA:
        xp:3
        coins:0.3
      CACTUS:
        xp:2
        coins:0.2
      SUGAR_CANE:
        xp:2
        coins:0.2
      BAMBOO:
        xp:3
        coins:0.3
      NETHER_WART:
        xp:4
        coins:0.4
    Fisher:
      ENCHANTED_BOOK:
        xp:20
        coins:20.0
      BOW:
        xp:20
        coins:20.0
      FISHING_ROD:
        xp:20
        coins:20.0
      NAUTILUS_SHELL:
        xp:30
        coins:50.0
      NAME_TAG
        xp:10
        coins:10.0
      SADDLE:
        xp:10
        coins:10.0
      COD:
        xp:5
        coins:3.0
      SALMON:
        xp:5
        coins:3.0
      PUFFERFISH:
        xp:5
        coins:3.0
      TROPICAL_FISH:
        xp:5
        coins:3.0
    Miner:
      STONE:
        xp:1
        coins:0.1
      BLACKSTONE:
        xp:1
        coins:0.1
      BASALT:
        xp:1
        coins:0.1
      COAL_ORE:
        xp:2
        coins:0.2
      IRON_ORE:
        xp:3
        coins:0.3
      GOLD_ORE:
        xp:4
        coins:0.4
      NETHER_GOLD_ORE:
        xp:4
        coins:0.4
      GILDED_BLACKSTONE:
        xp:4
        coins:0.4
      LAPIS_ORE:
        xp:4
        coins:0.4
      EMERALD_ORE:
        xp:6
        coins:1.0
      DIAMOND_ORE:
        xp:10
        coins:5.0
      REDSTONE_ORE:
        xp:3
        coins:0.3
      NETHER_QUARTZ_ORE:
        xp:4
        coins:0.4
      ANCIENT_DEBRIS:
        xp:50
        coins:25.0
      CRYING_OBSIDIAN:
        xp:20
        coins:10.0
      OBSIDIAN:
        xp:20
        coins:10.0
    MonsterSlayer:
      ENDER_DRAGON:
        xp:10000
        coins:6666.6
      WITHER:
        xp:1000
        coins:666.6
      WITHER_SKELETON:
        xp:50
        coins:16.6
      ELDER_GUARDIAN:
        xp:25
        coins:1.1
      GUARDIAN:
        xp:25
        coins:1.1
      IRON_GOLEM:
        xp:15
        coins:0.8
      GHAST:
        xp:15
        coins:0.8
      ENDERMAN:
        xp:10
        coins:0.5
      BLAZE:
        xp:10
        coins:0.5
      ZOMBIFIED_PIGLIN:
        xp:7
        coins:0.3
      PIGLIN:
        xp:7
        coins:0.3
      WITCH:
        xp:7
        coins:0.3
      CREEPER:
        xp:5
        coins:0.2
      ZOMBIE:
        xp:5
        coins:0.2
      ZOMBIE_VILLAGER:
        xp:5
        coins:0.2
      SKELETON:
        xp:5
        coins:0.2
      DROWNED:
        xp:5
        coins:0.2
      PHANTOM:
        xp:5
        coins:0.2
      SPIDER:
        xp:5
        coins:0.2
      CAVE_SPIDER:
        xp:5
        coins:0.2
    Woodcutter:
      ACACIA_LOG:
        xp:5
        coins:0.15
      BIRCH_LOG:
        xp:5
        coins:0.15
      DARK_OAK_LOG:
        xp:5
        coins:0.15
      JUNGLE_LOG:
        xp:5
        coins:0.15
      OAK_LOG:
        xp:5
        coins:0.15
      SPRUCE_LOG:
        xp:5
        coins:0.15
      CRIMSON_STEM:
        xp:5
        coins:0.15
      WARPED_STEM:
        xp:5
        coins:0.15
Users:
  2f9c5cc3-2a09-4f70-b58e-99db3d75317a:
    Job:
      Miner:
        Level: 1
        Xp: 0
      Woodcutter:
        Level: 1
        Xp: 0
      Fisher:
        Level: 1
        Xp: 0
      Farmer:
        Level: 1
        Xp: 0
      Breeder:
        Level: 1
        Xp: 0
      MonsterSlayer:
        Level: 1
        Xp: 0
      Digger:
        Level: 1
        Xp: 0
